### ISSUE TITLE
is possible to generate source code?

### ISSUE THREAD

**Issue by mikolaj24** [codeplea/genann#10]
I need function in C
output = answer(data)

Can You write mi this functionality? When I train my network i would like to use it in my program.

**Comment by codeplea** [comment]
I have no idea what you're trying to ask.

**Comment by mikolaj24** [comment]
i need function:
get learned network and print to stdout source code in C to using it.
all variables are no stored in file but in source code. no modyfication but very fast.

Simple i get code compile it and embeded in my code

**Comment by nurettin** [comment]
@mikolaj24 here's how all ANN libraries work: you create a neutral network, you train it, save it to disk;

    /* Saves the ann. */
    void genann_write(genann const *ann, FILE *out);

and load it to re-use the trained weights.

    /* Creates ANN from file saved with genann_write. */
    genann *genann_read(FILE *in);

**Comment by francescosisini** [comment]
I wrote a sci-fiction story about that (NN saved on disk) but only in italian. I am exactly looking for some one interested in translate it! You can find link to the story  in my profile ;)

**Comment by texrg** [comment]
@mikolaj24 or computer no have disk

**Comment by mikolaj24** [comment]
@texrg exactly

(and memory usage)
