### ISSUE TITLE
Fails to learn a simple example

### ISSUE THREAD

**Issue by fluxrider** [codeplea/genann#13]
I like your library, but unfortunately it doesn't seem to learn the simple examples I've tried. See y = x*x below. I'm sorry I can't help with a fix. Let me know if I've done something wrong. In this example, genann_run() returns 1 for any input instead of something close to the square.

#include <stdio.h>
#include <stdlib.h>
#include "genann.h"

int main(int argc, char *argv[])
{
    printf("GENANN example x^2.\n");
    printf("Train a small ANN to the x^2 function using backpropagation.\n");

    /* New network with 1 inputs,
     * 1 hidden layer of 2 neurons,
     * and 1 output. */
    genann *ann = genann_init(1, 1, 2, 1);

    /* Train */
    for(int i = 0; i < 10000; ++i) {
        double x = rand() % 10;
        double y = x * x;
        printf("Train with %.0f -> %.0f\n", x, y);
        genann_train(ann, &x, &y, .1);
    }

    /* Run the network and see what it predicts. */
    for(double x = 0; x < 10; x += .5) {
        printf("%.1f^2 -> %.0f\n", x, *genann_run(ann, &x));
    }

    genann_free(ann);
    return 0;
}

**Comment by fluxrider** [comment]
I've tried the FANN library from your external links recommendation. It looks like my problem is with the activation function. The range of the default activation function (sigmoid) is limited.
Sorry about that.

**Comment by codeplea** [comment]
It's really easy to change the activation function in genann. Try:

```
ann->activation_output = genann_act_linear;
```

That said, it almost always makes more sense to normalize/scale your data first.
