### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [codeplea/genann#19]
I would like to point out that identifiers like “[`__GENANN_H__`](https://github.com/codeplea/genann/blob/314ef383dd5b9631d47ddc5814c0568cd78f2001/genann.h#L27 "Update candidate")” and “[`__unused`](https://github.com/codeplea/genann/blob/314ef383dd5b9631d47ddc5814c0568cd78f2001/genann.c#L60 "Another update candidate")” [do eventually not fit](https://www.securecoding.cert.org/confluence/display/c/DCL37-C.+Do+not+declare+or+define+a+reserved+identifier "Do not use identifiers which are reserved for the compiler implementation.") to the expected naming convention of the C language standard.
Would you like to adjust your selection for unique names?

**Comment by codeplea** [comment]
I've fixed it. Thanks!
