### ISSUE TITLE
Genann test suite error

### ISSUE THREAD

**Issue by Starcounter-Jack** [codeplea/genann#2]
After building with *make*, I ran the test program with the following output:

```
GENANN TEST SUITE
	basic         pass: 7   fail: 0      0ms
	xor           pass: 5   fail: 0      0ms
	backprop      pass: 1   fail: 0      0ms
	train and     pass: 4   fail: 0      0ms
	train or      pass: 4   fail: 0      0ms
	train xor     test.c:189 (0.000000 != 1.000000)
pass: 3   fail: 1      0ms
	persist       pass:60765   fail: 0     93ms
	copy          pass:60765   fail: 0      0ms
	sigmoid       pass:400001   fail: 0      5ms
SOME TESTS FAILED (521555/521556)
```

Any clues to why this is?

**Comment by Starcounter-Jack** [comment]
Increasing the training epochs from 300 to 500 resolved the issue.

**Comment by codeplea** [comment]
Thanks for the feedback.

The networks are initialized randomly, so it seems like you got unlucky with the starting weights and required more training. I went ahead and increased the test training to 500 iterations anyway.

I suppose I could make the testing completely deterministic, but where would be the fun in that?
