### ISSUE TITLE
Addition of a build system generator

### ISSUE THREAD

**Issue by elfring** [codeplea/genann#20]
I suggest to reuse a higher level build system than [your current make script](https://github.com/codeplea/genann/blob/db51375bb71be871ca17132576b4b12ec49b779e/Makefile#L1 "Update candidate") so that powerful checks for software features will become easier.
- [CMake](https://cmake.org/ "Building software with CMake")
- [Autotools](https://www.gnu.org/software/autoconf/autoconf.html#introduction "Building software with Autoconf")

**Comment by codeplea** [comment]
There is a pull request adding CMake support here: https://github.com/codeplea/genann/pull/6

Can you tell me more about "powerful checks for software features"? I'm reluctant to add a new build system when Makefiles work fine, but maybe I'm missing the some advantage.

**Comment by elfring** [comment]
- Does [a tool like “autoscan”](https://www.gnu.org/savannah-checkouts/gnu/autoconf/manual/autoconf-2.69/html_node/autoscan-Invocation.html "Using autoscan to create configure.ac") show any software dependencies that you find worth for further considerations?
- How do you think about to support more development environments by [the reuse of build system generators](https://cmake.org/cmake/help/v3.12/manual/cmake-generators.7.html#cmake-generators "Listing of CMake generators")?

**Comment by keithalewis** [comment]
Cmake let's you build on more platforms. I submitted a PR that works on Windows with VC 2017. All the cool kids use cmake.:-)

**Comment by codeplea** [comment]
@keithalewis did you see PR https://github.com/codeplea/genann/pull/6 ?

**Comment by keithalewis** [comment]
@codeplea I did now. Sit tight, I am incorporating that into a new PR.

**Comment by keithalewis** [comment]
Nothing. I added VS 2017 support.

**Comment by keithalewis** [comment]
Reviewing my changes. I  did remove the shared library build franzflasch added. I need that for my Excel add-in implemenation of your code. https://github.com/keithalewis/xllgenann. It is possible to do both, but I was trying to keep things simple.

**Comment by the-kaustubh** [comment]
Can you please add into your Readme a section for others to contribute??? It'd be really helpful. 
Or just add a link to it
PS: great work!!

**Comment by letarg0** [comment]
or ninja, rake

**Comment by dodobyte** [comment]
> needing a build system for a single file .C library
get a job guys.

**Comment by franzflasch** [comment]
> There is a pull request adding CMake support here: #6
> 
> Can you tell me more about "powerful checks for software features"? I'm reluctant to add a new build system when Makefiles work fine, but maybe I'm missing the some advantage.

Sorry, seems i am late in this discussion. My PR #6 makes it easier to integrate genann in other projects. Sure makefiles are simple and easy, but I always need to write my own makefile if I want to use genann in other projects. With my solution it is built as a shared library and can easily be linked into any other projects without fiddling around with makefiles.
