### ISSUE TITLE
Why rand() has no seed?

### ISSUE THREAD

**Issue by crazyBaboon** [codeplea/genann#27]
I am sure there must be a good reason why the **srand** seed is not used to feed rand(). What it the reason?

Basically, without using **srand**, untrained neural networks will always output the same value given the same input.

**Comment by codeplea** [comment]
> Basically, without using srand, untrained neural networks will always output the same value given the same input.

That is exactly what I want from `test.c`, as I don't want tests to randomly fail because of luck.

I could probably add srand into the examples, just haven't done so yet.

See here: https://github.com/codeplea/genann/issues/4

**Comment by crazyBaboon** [comment]
would you not need to add it to gennan.c (and the **#include <time.h>** header)?
