### ISSUE TITLE
-nan Assertion Error

### ISSUE THREAD

**Issue by Pakleni** [codeplea/genann#33]
When the activation_output and activation_hidden functions are set to sigmoid_cached, every once in a while, the assertion error pops up.
p.s. i'm quite new to neural networks and was using your code to learn.

**Comment by Pakleni** [comment]
If i set them to linear, the output ann's weights all become nan's

**Comment by kasey-** [comment]
@Pakleni can you share your platform, compiler, and your NN topology? Ideally your code?
Did you tried using `genann_act_sigmoid` instead of `genann_act_sigmoid_cached` ?
On my side, I played a bit with this lib and never got this error.
