### ISSUE TITLE
Feature Extraction

### ISSUE THREAD

**Issue by mbeddeveloper** [codeplea/genann#37]
In example4.c there is an example (l. 96) where features where extracted column per column from an file in the genann_train function. Is there a way to extract picked features? Or does anyone have an idea or suggestions how to implement that?

**Comment by codeplea** [comment]
The training data is read from the file starting on line [18](https://github.com/codeplea/genann/blob/122243f9449b3e33a4e11450b70c10576d4559d7/example4.c#L18). On line [96](https://github.com/codeplea/genann/blob/122243f9449b3e33a4e11450b70c10576d4559d7/example4.c#L96), which you mention, the data is already is memory and is then being trained into the neural network.

Anyway, I don't understand what you're asking for. What do you mean by *extract* and *picked features*.

**Comment by mbeddeveloper** [comment]
I have a dataset with 121 features (array 0 - 120) in the example4.c it's 4 features. i want to extract for example feature 0, 4, 8, 9, 12, ... from the 121 feature dataset or for example not the first eleven rather then start on position 11-21. You understand what i mean?
