### ISSUE TITLE
Error when trying to compile with G++ + bionic

### ISSUE THREAD

**Issue by FlamingHub** [codeplea/genann#38]
The following error speears when trying to conpile with G++ + bionic
/genann-master/genann.c: In function 'genann* genann_init(int, int, int, int)':
/genann-master/genann.c:123:25: error: invalid conversion from 'void*' to 'genann*' [-fpermissive]
compilation terminated due to -Wfatal-errors.

**Comment by codeplea** [comment]
This is a C library. Why are you trying to compile it as C++?

Use `gcc`, not `g++`.
