### ISSUE TITLE
DOS port

### ISSUE THREAD

**Issue by eltoneo** [codeplea/genann#39]
Without reinventing from scratch, has a MS C 5.1 build of genann available to DOS coder's?
thx
eltoneo

**Comment by codeplea** [comment]
I have no idea what that compiler supports. genann isn't a lot of code. You could probably manually fix any errors, if any, without much effort.

**Comment by eltoneo** [comment]
On Nov 19, 2019, at 9:56 PM, Lewis Van Winkle wrote:

> I have no idea what that compiler supports. genann isn't a lot of code. You could probably manually fix any errors, if any, without much effort.
> 
> 
Dear Lewis Van Winkle:
I’m using the 5.1 compiler with FreeDOS 1.2 in VirtualBox.
Also, I’m transitioning from BASIC to C, so please accept my ignorance.
What I’ve noticed is that this compiler is more finicky, compared to other’s.
e.g., arrays need to be defined before ‘main’, from my limited experience.

The reason for yesterday’s post was that ‘example1.c’  failed to open, reporting:
“CANNOT EDIT BINARY FILES”

I then opened it with another editor and saved it to ‘EXAM1.C’, which compiler accepted.
The compiler error’s shown below are all foreign to me and need help understanding.
Sincerely,
eltoneo  

https://winworldpc.com/product/microsoft-c-c/5x

https://www.osboxes.org/freedos/

C:\C51\EXAM1.C
C:\C51\EXAM1.C(16) : error C2144: syntax error : missing ';' before type 'undefined'
C:\C51\EXAM1.C(17) : error C2144: syntax error : missing ';' before type 'undefined'
C:\C51\EXAM1.C(18) : error C2144: syntax error : missing ';' before type 'int'
C:\C51\EXAM1.C(23) : error C2065: 'ann' : undefined
C:\C51\EXAM1.C(23) : error C2117: '*' : illegal for struct/union
C:\C51\EXAM1.C(23) : error C2106: '=' : left operand must be lvalue
C:\C51\EXAM1.C(26) : error C2065: 'i' : undefined
C:\C51\EXAM1.C(27) : warning C4047: 'argument' : different levels of indirection
C:\C51\EXAM1.C(27) : warning C4024: 'genann_train' : different types : parameter 1
C:\C51\EXAM1.C(27) : error C2065: 'input' : undefined
C:\C51\EXAM1.C(27) : error C2109: subscript on non-array
C:\C51\EXAM1.C(27) : error C2065: 'output' : undefined
C:\C51\EXAM1.C(27) : warning C4047: 'argument' : different levels of indirection
C:\C51\EXAM1.C(27) : warning C4024: 'genann_train' : different types : parameter 2
C:\C51\EXAM1.C(27) : warning C4047: 'argument' : different levels of indirection
C:\C51\EXAM1.C(27) : warning C4024: 'genann_train' : different types : parameter 3
C:\C51\EXAM1.C(27) : warning C4021: 'genann_train' : too few actual parameters
C:\C51\EXAM1.C(28) : warning C4047: 'argument' : different levels of indirection
C:\C51\EXAM1.C(28) : warning C4024: 'genann_train' : different types : parameter 1
C:\C51\EXAM1.C(28) : error C2109: subscript on non-array
C:\C51\EXAM1.C(28) : warning C4047: 'argument' : different levels of indirection
C:\C51\EXAM1.C(28) : warning C4024: 'genann_train' : different types : parameter 2
C:\C51\EXAM1.C(28) : warning C4047: 'argument' : different levels of indirection
C:\C51\EXAM1.C(28) : warning C4024: 'genann_train' : different types : parameter 3
C:\C51\EXAM1.C(28) : warning C4021: 'genann_train' : too few actual parameters
C:\C51\EXAM1.C(29) : warning C4047: 'argument' : different levels of indirection
C:\C51\EXAM1.C(29) : warning C4024: 'genann_train' : different types : parameter 1
C:\C51\EXAM1.C(29) : error C2109: subscript on non-array
C:\C51\EXAM1.C(29) : warning C4047: 'argument' : different levels of indirection
C:\C51\EXAM1.C(29) : warning C4024: 'genann_train' : different types : parameter 2
C:\C51\EXAM1.C(29) : warning C4047: 'argument' : different levels of indirection
C:\C51\EXAM1.C(29) : warning C4024: 'genann_train' : different types : parameter 3
C:\C51\EXAM1.C(29) : warning C4021: 'genann_train' : too few actual parameters
C:\C51\EXAM1.C(30) : warning C4047: 'argument' : different levels of indirection
C:\C51\EXAM1.C(30) : warning C4024: 'genann_train' : different types : parameter 1
C:\C51\EXAM1.C(30) : error C2109: subscript on non-array
C:\C51\EXAM1.C(30) : warning C4047: 'argument' : different levels of indirection
C:\C51\EXAM1.C(30) : warning C4024: 'genann_train' : different types : parameter 2
C:\C51\EXAM1.C(30) : warning C4047: 'argument' : different levels of indirection
C:\C51\EXAM1.C(30) : warning C4024: 'genann_train' : different types : parameter 3
C:\C51\EXAM1.C(30) : warning C4021: 'genann_train' : too few actual parameters
C:\C51\EXAM1.C(34) : error C2065: 'input' : undefined
C:\C51\EXAM1.C(34) : error C2109: subscript on non-array
C:\C51\EXAM1.C(34) : error C2109: subscript on non-array
C:\C51\EXAM1.C(34) : warning C4047: 'argument' : different levels of indirection
C:\C51\EXAM1.C(34) : warning C4024: 'genann_run' : different types : parameter 1
C:\C51\EXAM1.C(34) : error C2109: subscript on non-array
C:\C51\EXAM1.C(34) : warning C4021: 'genann_run' : too few actual parameters
C:\C51\EXAM1.C(35) : error C2109: subscript on non-array
C:\C51\EXAM1.C(35) : error C2109: subscript on non-array
C:\C51\EXAM1.C(35) : warning C4047: 'argument' : different levels of indirection
C:\C51\EXAM1.C(35) : warning C4024: 'genann_run' : different types : parameter 1
C:\C51\EXAM1.C(35) : error C2109: subscript on non-array
C:\C51\EXAM1.C(35) : warning C4021: 'genann_run' : too few actual parameters
C:\C51\EXAM1.C(36) : error C2109: subscript on non-array
C:\C51\EXAM1.C(36) : error C2109: subscript on non-array
C:\C51\EXAM1.C(36) : warning C4047: 'argument' : different levels of indirection
C:\C51\EXAM1.C(36) : warning C4024: 'genann_run' : different types : parameter 1
C:\C51\EXAM1.C(36) : error C2109: subscript on non-array
C:\C51\EXAM1.C(36) : warning C4021: 'genann_run' : too few actual parameters
C:\C51\EXAM1.C(37) : error C2109: subscript on non-array
C:\C51\EXAM1.C(37) : error C2109: subscript on non-array
C:\C51\EXAM1.C(37) : warning C4047: 'argument' : different levels of indirection
C:\C51\EXAM1.C(37) : warning C4024: 'genann_run' : different types : parameter 1
C:\C51\EXAM1.C(37) : error C2109: subscript on non-array
C:\C51\EXAM1.C(37) : warning C4021: 'genann_run' : too few actual parameters
C:\C51\EXAM1.C(39) : warning C4047: 'argument' : different levels of indirection
C:\C51\EXAM1.C(39) : warning C4024: 'genann_free' : different types : parameter 1
> —

**Comment by codeplea** [comment]
What are you trying to accomplish by using a compiler from 1987? If you switch to a modern, standards-compliant compiler, you'll save yourself a lot of hassle.
