### ISSUE TITLE
There no srand in examples

### ISSUE THREAD

**Issue by aleksei-udalov** [codeplea/genann#4]
Hi, at first thank you for this simple and interesting software!
I get a problem like in issue 2, example1 doesn't work right (but tests passed):
```
$ ./example1
GENANN example 1.
Train a small ANN to the XOR function using backpropagation.
Output for [0, 0] is 0.
Output for [0, 1] is 1.
Output for [1, 0] is 1.
Output for [1, 1] is 1.
```
This result always the same and depends only on test training duration.
I found srand function never used in examples or the lib:
```
$ ack-grep srand
test.c
261:    srand(100)
```
In test.c srand has constant argument. In this way, neural network always initialized with the same data.
`The C library function void srand(unsigned int seed) seeds the random number generator used by the function rand.`
I think that srand have to be included into every example:
```
#include <time.h>
...
srand(time(NULL));
```

**Comment by glouw** [comment]
The examples are meant to show how to use genaan. I don't think they're there for accuracy.

**Comment by codeplea** [comment]
The constant `srand()` in `test.c` is that way on purpose. The idea being that the test results should be deterministic.

It's probably a good idea to add `srand()` into the examples. I might do that.

**Comment by codeplea** [comment]
I've added `srand(time(0));` to the examples.
