### ISSUE TITLE
Anything about C++?

### ISSUE THREAD

**Issue by FlamingArr** [codeplea/genann#40]
I am trying to use a simple NN library in a *C++* program but genann is for C not C++
Can you please make a C++ version or reccomend smth similiar?

**Comment by fennecdjay** [comment]
IMHO, there is no need for a C++ version.
It is just a matter of compiling and linking using appropriate tools, as the you can call C code from C++.
Look this [stack-overflow](https://stackoverflow.com/questions/16850992/call-a-c-function-from-c-code) for further information.

Hope it helps.
Good luck.

**Comment by leonardoInf** [comment]
Well, you have to cast two pointers on lines 121 and 183 but the compiler will warn you about that
