### ISSUE TITLE
Prediction

### ISSUE THREAD

**Issue by IIITimIII** [codeplea/genann#47]
Hi, I just started working with genann and I'm trying to fix this issue for days already.
This is my first training run:
![image](https://user-images.githubusercontent.com/76436362/102780057-942b8400-4395-11eb-883c-1deb9e68c8d5.png)

Seems to work pretty good.
If I save the net and use it ffor a predicition with neraly the same input this is the output:
![image](https://user-images.githubusercontent.com/76436362/102780226-d81e8900-4395-11eb-8ba7-1ce15322253d.png)

The purple graph is the target and the green one the output of my nn.

**Comment by codeplea** [comment]
Post the smallest amount of code that demonstrates your problem.

**Comment by ScratchyCode** [comment]
Genann actually work fine with classification problem, it implement only sigmoind activation function.
Your problem is a regression, no?

**Comment by ScratchyCode** [comment]
Genann actually work fine with classification problem, it implement only sigmoind activation function.
But you want to do a regression, right?

**Comment by ScratchyCode** [comment]
Genann actually work fine with classification problem, it implement only sigmoid activation function.
But you want to do a regression, right

**Comment by ScratchyCode** [comment]
Genann actually work fine with classification problem, it implement only sigmoid activation function.
But you want to do a regression, right?

**Comment by ScratchyCode** [comment]
I have a question about regression
