### ISSUE TITLE
input data

### ISSUE THREAD

**Issue by 0xtrzy** [codeplea/genann#49]
input data is form 0 .. 1 or -1 to +1 ?

**Comment by codeplea** [comment]
Genann uses the sigmoid function by default: https://en.wikipedia.org/wiki/Sigmoid_function

So each neuron *output* is from 0 to 1.

Neuron *inputs* don't really matter. Part of NN learning is finding what weight/scale to apply to neuron inputs, so it should work just fine with either range. The only issue is that some learning methods will break down if the inputs are on the "flat" part of the sigmoid curve (e.g. inputs less than -5 or more than +5 may not work as well).

**Comment by fab1an2** [comment]
I receive sometimes output  **-1** not only 0...1

**Comment by codeplea** [comment]
> I receive sometimes output **-1** not only 0...1

This is the sigmoid function from genann:

```
double genann_act_sigmoid(const genann *ann unused, double a) {
    if (a < -45.0) return 0;
    if (a > 45.0) return 1;
    return 1.0 / (1 + exp(-a));
}
```

It's impossible for it to return **-1**.

Of course you can change the output function to whatever you want, and get whatever you want. But it does use sigmoid by default.
