### ISSUE TITLE
OCR example?

### ISSUE THREAD

**Issue by IvanJRCH** [codeplea/genann#55]
How can I present the pixel data to Gennan so that he can tell me if an image is a specific letter? could you give me an example

**Comment by codeplea** [comment]
You can input pixel data in the same way as any other input - you'll just need a lot more inputs. See the existing examples.

**Comment by IvanJRCH** [comment]
hello thanks for your answer, i asked this same question on stackoverflow

https://stackoverflow.com/questions/75414288/how-to-pass-the-pixels-of-the-image-to-the-neural-network-with-genann

https://ai.stackexchange.com/questions/39102/how-to-pass-the-pixels-of-the-image-to-the-neural-network-with-genann

but apparently no one knows the answer, and I tried it but the network does not give me correct data, in the links to stackoverflow is the program that I am testing, I used this library to load the images https://github.com/nothings/ stb I am using the dev-c++ IDE the image 0.jpg is a letter "A" drawn with paint, the image 1.jpg AND 3.jpg is the letter "B" but a little different from each other, I really appreciate your help


Enviado desde Outlook<http://aka.ms/weboutlook>

________________________________
De: Lewis Van Winkle ***@***.***>
Enviado: miércoles, 15 de febrero de 2023 12:01 a. m.
Para: codeplea/genann ***@***.***>
Cc: IvanJRCH ***@***.***>; Author ***@***.***>
Asunto: Re: [codeplea/genann] OCR example? (Issue #55)


You can input pixel data in the same way as any other input - you'll just need a lot more inputs. See the existing examples.

**Comment by codeplea** [comment]
It's not that nobody knows the answer, it's that you're asking other people to do a lot of work for you. What you're trying to do isn't hard or complicated. It just requires a decent bit of code.

The stb library is great, and I think that's your best bet to read in pixel data. Then you simply need to feed that pixel data to genann. Before you do that though, you should start with something simpler so you can learn how everything works.  Seriously, start with images that are 1 pixel. Train the network that one black pixel is A, one white pixel is B, or whatever. Learn how it works. If anything is not clear, try again with 2x2 images. If you can do that, then expand to your bigger images.

I hope that advice helps.

**Comment by IvanJRCH** [comment]
Thanks for answering, that's a good idea, I'll try it.

Obtener Outlook para Android<https://aka.ms/AAb9ysg>
________________________________
