### ISSUE TITLE
Can it be used for inference on ESP32? 

### ISSUE THREAD

**Issue by ZJDATY** [codeplea/genann#60]
The main frequency of ESP32-S3 can reach up to 240MHz. What problems may I encounter?

**Comment by codeplea** [comment]
What do you mean? Why would you have any problems with that?

**Comment by ZJDATY** [comment]
> What do you mean? Why would you have any problems with that?

Hi,I just think it would be an interesting thing. I saw someone using esp32 to reason about AI, and I happened to see your article on AI training and reasoning that does not rely on any third-party libraries.

**Comment by codeplea** [comment]
Genann should work great on the ESP32. I know others are using it there, and even on smaller chips too.
