### ISSUE TITLE
Beautiful work

### ISSUE THREAD

**Issue by glouw** [codeplea/genann#9]
Not an issue, I just wanted to commend you for your excellent contribution. Its hard finding stuff as small and powerful as this.

Well done.

**Comment by codeplea** [comment]
I'm glad you like it. Thanks for the kind words!

**Comment by glouw** [comment]
Codeplea, you inspired me to investigate ANNs a little deeper (no pun intended). I wrote my own (single hidden layer vs. genann's multi layers).

Please check it out!

https://github.com/glouw/tinn

**Comment by codeplea** [comment]
Great work @glouw ! I'll add a link to it from the readme.

If Genann inspired tinn, would you mind adding a link to Genann from your project? It should be helpful for people that need more than a single hidden layer.

**Comment by glouw** [comment]
Great, thanks. I added Genann in my readme.
